### ISSUE TITLE
CeSymm runs are not independent

### ISSUE THREAD

**Issue by sbliven** [rcsb/symmetry#29]
Some information is leaked between runs of CeSymm. The can be demonstrated by running the following test (which should be included in CeSymmTest) with assertion enabled:

```java
	public void testIndependence() throws IOException, StructureException {
		String name;

		// Perform alignment to determine axis
		Atom[] ca1, ca2;
		AFPChain alignment;
		RotationAxis axis;
		double[] coefs,expectedHarmonics;

		CeSymm ce = new CeSymm();
		
		name = "1MER.A";
		ca1 = StructureTools.getAtomCAArray(StructureTools.getStructure(name));
		ca2 = StructureTools.cloneCAArray(ca1);
		alignment = ce.align(ca1, ca2);

		//ce = new CeSymm();// work around bug

		name = "1ijq.A:377-641";
		ca1 = StructureTools.getAtomCAArray(StructureTools.getStructure(name));
		ca2 = StructureTools.cloneCAArray(ca1);
		alignment = ce.align(ca1, ca2);
	}
```

It causes an AssertionError in CeCPMain.java:165 in postProcessAlignment, indicating that either the matrix or the alignment lengths are being leaked from the first assignment.  Creating a fresh CeSymm instance for each run fixes the error.

There is also a commented-out test in CeSymmTest which likely is related to this bug. CECP should also be checked to see if this bug applies.

**Comment by lafita** [comment]
I fixed this in a biojava commit [c1b7951](https://github.com/biojava/biojava/commit/c1b795186de2bf600cb40cd8e0540d788c99fb6b). I created the Test proposed by @sbliven and no error occurs. I tried to reduce as much as possible the member variables of CeSymm and reset them every "align" call, so that the same object with the same parameters can be used to analyze other structures.
