### ISSUE TITLE
CE-Symm uses trivial alignment in d1n7na1

### ISSUE THREAD

**Issue by dmyersturnbull** [rcsb/symmetry#33]
http://source.rcsb.org/jfatcatserver/showSymmetry.jsp?name1=d1n7na1

**Comment by lafita** [comment]
This problem might be the same bug that occurred when performing multiple alignments blacking out the previous ones. It was caused because during the optimization step, after the alignment, the black regions were not considered and the aligned fragments could fall inside. This is now fixed in CeSymm.

I tried for all the cases mentioned here and no trivial alignment regions are used. As an example d1n7na1 gives the following output:

![d1n7na1_trivial_bug](https://cloud.githubusercontent.com/assets/11161522/7163608/42dc842e-e39b-11e4-855a-90fe8a6756fb.png)

**Comment by andreasprlic** [comment]
nice!

**Comment by dmyersturnbull** [comment]
This fix just made my day! Thanks!
