### ISSUE TITLE
CE-Symm uses default max gap size

### ISSUE THREAD

**Issue by sbliven** [rcsb/symmetry#42]
CE-CP has always set the max gap size to 0 to allow the large insertions that tend to appear at the CP boundary. However, CE-Symm neglects to make this change, so it uses the default gap size of 30.

**Comment by lafita** [comment]
Why isn't this change incorporated in the master branch @sbliven? 

CESymmParameters continues extending CEParameters instead of CECPParameters. It makes sense to change it, since the algorithm we use is the CECP, and with the refinement I think the results are now more robust to these little differences in the initial alignment.

Should we merge this change?

**Comment by lafita** [comment]
The **CECPParameters** gave worst results than the **CEParameters**, so it was decided to keep them unchanged. Closing this.
