### ISSUE TITLE
Display order more clearly in output

### ISSUE THREAD

**Issue by sbliven** [rcsb/symmetry#64]
We should indicate the point group(s), order, and number of repeats more clearly in the output.

**Comment by lafita** [comment]
This could be linked with the **Data Structure** for storing PG and hierarchical symmetry. If we provide a method to serialize it we could store it and report the symmetry in the output.

**Comment by lafita** [comment]
The option *-verbose* (default for less than 10 structures and non batch mode, the same as the Jmol 3D visualization) prints a short description of the **CeSymm** results, so that the user can get an idea. An example description can be:

<pre>
4I4Q could be refined into symmetry order 4
2BUF.H could not be refined (asymmetric)
</pre>

To obtain all the scores and statistics of the results, the option *-stats* can be used (stored in a tsv file). In there, the PG, order, etc. information can be found in a parsable format.
