### ISSUE TITLE
Better visualization of multiple axes

### ISSUE THREAD

**Issue by sbliven** [rcsb/symmetry#72]
The visualization of multiple axes is very inconsistent now.

Consider 2pel.A:,D:,B:,C: (order required for the full alignment). This is composed of two levels of C2 symmetry. The default view shows only the top level, so one might think it had detected order 2. The initial view should show all axes detected.

<img width="1147" alt="screen shot 2015-11-06 at 12 16 15" src="https://cloud.githubusercontent.com/assets/595872/10995851/341c03ca-8480-11e5-8235-2c04373467ac.png">

Viewing either the subunit superposition or the multiple superposition does show the additional axes, but it is hard to distinguish which subunits the axes relate because they are drawn across the full complex. They should be drawn only around the repeats they relate. Furthermore, when multiple structures are shown in the multiple alignment view, it is very difficult to see which axis generates each model.

**Comment by lafita** [comment]
This is tricky and needs a more powerful data structure for storing the axes of symmetry (that contains the Atoms to which the axes apply, for example). For now I set the default as showing all the axes in the initial view, although it is sometimes a bit messy (specially when the recursive version finds many levels of symmetry).

**Comment by sbliven** [comment]
@lafita Do you have an example where we find too many levels of symmetry?

**Comment by lafita** [comment]
The DNA clamps, for example, have 3 levels (the three chains with C3, each chain is two fold C2, and each part is two fold again C2), for a combined D6 symmetry. The axes in this case appear to be mixed (because they cross all the protein, we should restrict them to the part they apply only and possibly coloring them according to a symmetry level can help). That is why I thought that showing only the overall PG and coloring the subunits was cleaner than showing all the axes (at the current state).

**Comment by lafita** [comment]
This is a sub-issue of #77
