### ISSUE TITLE
Poor handling of short repeats

### ISSUE THREAD

**Issue by sbliven** [rcsb/symmetry#88]
1. The --simple output gives the message "Refinement was not significant (TM=0.63)" (e.g. for 1l0s.A) if the refinement doesn't meet the minlen threshold. It should give a more informative message like "Repeats were too short (core-length=5)"
2. (Bonus) Short repeats should be combined to make longer repeats, rather than rejecting it altogether.

**Comment by lafita** [comment]
I see some complications in combining short repeats into longer ones, because the final length of the repeats is only known after optimization. Thus, it would require an additional optimization after merging some of the repeats. 

In addition, we would need to know the optimal factor of the number of repeats to combine. For example:

- for 6 short repeats, should we combine 2 or 3 of them? 
- and what should we do for 7 short repeats, drop the highest RMSD terminal residue?

On the one hand I agree that the repeat number and length is very much dependent on the optimal self-alignment, and that is a problem for short **OPEN** repeats. The order detector has less information than for **CLOSED** repeats.
On the other hand, this only applies to very short repeats (less than 15 residues), which have generally poor signal and are better detected by other algorithms (solenoid or TPR detection), so **CE-Symm** is not the optimal approach for detecting them.

**Comment by sbliven** [comment]
v2.3.0 fixes the exception that was thrown for short repeats (#118) but the issue of poor feedback as to the reason for rejection stands.

```sh
$ ./runCESymm.sh  --stats -- 1l0s.A
Name    NumRepeats      SymmGroup       Refined SymmLevels      SymmType        RotationAngle   ScrewTranslation        UnrefinedTMscore     UnrefinedRMSD   SymmTMscore     SymmRMSD        RepeatLength    CoreLength      Length  Coverage        Repeats
1l0s.A  1       C1      true    1       OPEN    121.80  3.19    0.64    1.73    0.63    1.20    10      42      88      0.75    1L0S.A_3-8;1L0S.A_10-19;1L0S.A_20-29;1L0S.A_30-39;1L0S.A_40-49;1L0S.A_50-59;1L0S.A_62-71
CA2[0]=(30.77,52.63,41.00)
$ ./runCESymm.sh  --minlen=5 --stats -- 1l0s.A
Name    NumRepeats      SymmGroup       Refined SymmLevels      SymmType        RotationAngle   ScrewTranslation        UnrefinedTMscore     UnrefinedRMSD   SymmTMscore     SymmRMSD        RepeatLength    CoreLength      Length  Coverage        Repeats
1l0s.A  7       H       true    1       OPEN    120.36  3.14    0.64    1.73    0.67    0.74    10      42      88      0.75    1L0S.A_3-8;1L0S.A_9-19;1L0S.A_20-29;1L0S.A_30-39;1L0S.A_40-49;1L0S.A_50-59;1L0S.A_62-71
```

I think I will close this as 'wontfix' since combining repeats seems problematic.
